Money1 = open("Accounts1/Money1.txt").read()
Money2 = open("Accounts1/Money2.txt").read()
Money3 = open("Accounts1/Money3.txt").read()
Money4 = open("Accounts1/Money4.txt").read()
Money5 = open("Accounts1/Money5.txt").read()
Money6 = open("Accounts1/Money6.txt").read()
Money7 = open("Accounts1/Money7.txt").read()
Money8 = open("Accounts1/Money8.txt").read()
Money9 = open("Accounts1/Money9.txt").read()
Money10 = open("Accounts1/Money10.txt").read()
Money11 = open("Accounts1/Money11.txt").read()
Money12 = open("Accounts1/Money12.txt").read()
Money13 = open("Accounts1/Money13.txt").read()
Money14 = open("Accounts1/Money14.txt").read()
Money15 = open("Accounts1/Money15.txt").read()
Money16 = open("Accounts1/Money16.txt").read()
Money17 = open("Accounts1/Money17.txt").read()
Money18 = open("Accounts1/Money18.txt").read()
Money19 = open("Accounts1/Money19.txt").read()
Money20 = open("Accounts1/Money20.txt").read()
Money21 = open("Accounts1/Money21.txt").read()
Money22 = open("Accounts1/Money22.txt").read()
Money23 = open("Accounts1/Money23.txt").read()
Money24 = open("Accounts1/Money24.txt").read()
Money25 = open("Accounts1/Money19.txt").read()
Money26 = open("Accounts1/Money20.txt").read()
Money27 = open("Accounts1/Money21.txt").read()
Money28 = open("Accounts1/Money22.txt").read()
Money29 = open("Accounts1/Money23.txt").read()
Money30 = open("Accounts1/Money24.txt").read()

while True:
    Choice1 = input('''Would you like to see the balance of a student (B),
deposit money (D) or withdraw money (W)? ''')
    while Choice1 != 'b' and Choice1 != 'd' and Choice1 != 'w':
        Choice1 = input("Not a valid answer, please try again: ")
    if Choice1 == 'b':
        Choice2 = input("Type the Student ID number here: ")
        while Choice2 != '1' and Choice2 != '2' and Choice2 != '3' and Choice2 != '4' and Choice2 != '5' and Choice2 != '6' and Choice2 != '7' and\
        Choice2 != '8' and Choice2 != '9' and Choice2 != '10' and Choice2 != '11' and Choice2 != '12' and Choice2 != '13' and Choice2 != '14' and\
        Choice2 != '15' and Choice2 != '16' and Choice2 != '17' and Choice2 != '18' and Choice2 != '19' and Choice2 != '20' and Choice2 != '21' and\
        Choice2 != '22' and Choice2 != '23' and Choice2 != '24' and Choice2 != '25' and Choice2 != '26' and Choice2 != '27' and\
        Choice2 != '28' and Choice2 != '29' and Choice2 != '30':
            Choice2 = input("Not a valid ID, please try again: ")
        if Choice2 == '1':
            file = open('Accounts1/Money1.txt', 'w')
            file.write(str(Money1))
            file.close()
            print(open("Accounts1/Money1.txt").read())
        elif Choice2 == '2':
            file = open('Accounts1/Money2.txt', 'w')
            file.write(str(Money2))
            file.close()
            print(open("Accounts1/Money2.txt").read())
        elif Choice2 == '3':
            file = open('Accounts1/Money3.txt', 'w')
            file.write(str(Money3))
            file.close()
            print(open("Accounts1/Money3.txt").read())
        elif Choice2 == '4':
            file = open('Accounts1/Money4.txt', 'w')
            file.write(str(Money4))
            file.close()
            print(open("Accounts1/Money4.txt").read())
        elif Choice2 == '5':
            file = open('Accounts1/Money5.txt', 'w')
            file.write(str(Money5))
            file.close()
            print(open("Accounts1/Money5.txt").read())
        elif Choice2 == '6':
            file = open('Accounts1/Money6.txt', 'w')
            file.write(str(Money6))
            file.close()
            print(open("Accounts1/Money6.txt").read())
        elif Choice2 == '7':
            file = open('Accounts1/Money7.txt', 'w')
            file.write(str(Money7))
            file.close()
            print(open("Accounts1/Money7.txt").read())
        elif Choice2 == '8':
            file = open('Accounts1/Money8.txt', 'w')
            file.write(str(Money8))
            file.close()
            print(open("Accounts1/Money8.txt").read())
        elif Choice2 == '9':
            file = open('Accounts1/Money9.txt', 'w')
            file.write(str(Money9))
            file.close()
            print(open("Accounts1/Money9.txt").read())
        elif Choice2 == '10':
            file = open('Accounts1/Money10.txt', 'w')
            file.write(str(Money10))
            file.close()
            print(open("Accounts1/Money10.txt").read())
        elif Choice2 == '11':
            file = open('Accounts1/Money11.txt', 'w')
            file.write(str(Money11))
            file.close()
            print(open("Accounts1/Money11.txt").read())
        elif Choice2 == '12':
            file = open('Accounts1/Money12.txt', 'w')
            file.write(str(Money12))
            file.close()
            print(open("Accounts1/Money12.txt").read())
        elif Choice2 == '13':
            file = open('Accounts1/Money13.txt', 'w')
            file.write(str(Money13))
            file.close()
            print(open("Accounts1/Money13.txt").read())
        elif Choice2 == '14':
            file = open('Accounts1/Money14.txt', 'w')
            file.write(str(Money14))
            file.close()
            print(open("Accounts1/Money14.txt").read())
        elif Choice2 == '15':
            file = open('Accounts1/Money15.txt', 'w')
            file.write(str(Money15))
            file.close()
            print(open("Accounts1/Money15.txt").read())
        elif Choice2 == '16':
            file = open('Accounts1/Money16.txt', 'w')
            file.write(str(Money16))
            file.close()
            print(open("Accounts1/Money16.txt").read())
        elif Choice2 == '17':
            file = open('Accounts1/Money17.txt', 'w')
            file.write(str(Money17))
            file.close()
            print(open("Accounts1/Money17.txt").read())
        elif Choice2 == '18':
            file = open('Accounts1/Money18.txt', 'w')
            file.write(str(Money18))
            file.close()
            print(open("Accounts1/Money18.txt").read())
        elif Choice2 == '19':
            file = open('Accounts1/Money19.txt', 'w')
            file.write(str(Money19))
            file.close()
            print(open("Accounts1/Money19.txt").read())
        elif Choice2 == '20':
            file = open('Accounts1/Money20.txt', 'w')
            file.write(str(Money20))
            file.close()
            print(open("Accounts1/Money20.txt").read())
        elif Choice2 == '21':
            file = open('Accounts1/Money21.txt', 'w')
            file.write(str(Money21))
            file.close()
            print(open("Accounts1/Money21.txt").read())
        elif Choice2 == '22':
            file = open('Accounts1/Money22.txt', 'w')
            file.write(str(Money22))
            file.close()
            print(open("Accounts1/Money22.txt").read())
        elif Choice2 == '23':
            file = open('Accounts1/Money23.txt', 'w')
            file.write(str(Money23))
            file.close()
            print(open("Accounts1/Money23.txt").read())
        elif Choice2 == '24':
            file = open('Accounts1/Money24.txt', 'w')
            file.write(str(Money24))
            file.close()
            print(open("Accounts1/Money24.txt").read())
        elif Choice2 == '25':
            file = open('Accounts1/Money25.txt', 'w')
            file.write(str(Money25))
            file.close()
            print(open("Accounts1/Money25.txt").read())
        elif Choice2 == '26':
            file = open('Accounts1/Money26.txt', 'w')
            file.write(str(Money26))
            file.close()
            print(open("Accounts1/Money26.txt").read())
        elif Choice2 == '27':
            file = open('Accounts1/Money27.txt', 'w')
            file.write(str(Money27))
            file.close()
            print(open("Accounts1/Money27.txt").read())
        elif Choice2 == '28':
            file = open('Accounts1/Money28.txt', 'w')
            file.write(str(Money28))
            file.close()
            print(open("Accounts1/Money28.txt").read())
        elif Choice2 == '23':
            file = open('Accounts1/Money29.txt', 'w')
            file.write(str(Money29))
            file.close()
            print(open("Accounts1/Money29.txt").read())
        elif Choice2 == '30':
            file = open('Accounts1/Money30.txt', 'w')
            file.write(str(Money30))
            file.close()
            print(open("Accounts1/Money30.txt").read())
    elif Choice1 == 'd':
        DepositAmount = input('How much do you want to deposit? $')
        Choice2 = input("Type the Student ID number here: ")
        while Choice2 != '1' and Choice2 != '2' and Choice2 != '3' and Choice2 != '4' and Choice2 != '5' and Choice2 != '6' and Choice2 != '7' and\
        Choice2 != '8' and Choice2 != '9' and Choice2 != '10' and Choice2 != '11' and Choice2 != '12' and Choice2 != '13' and Choice2 != '14' and\
        Choice2 != '15' and Choice2 != '16' and Choice2 != '17' and Choice2 != '18' and Choice2 != '19' and Choice2 != '20' and Choice2 != '21' and\
        Choice2 != '22' and Choice2 != '23' and Choice2 != '24' and Choice2 != '25' and Choice2 != '26' and Choice2 != '27' and\
        Choice2 != '28' and Choice2 != '29' and Choice2 != '30':
            Choice2 = input("Not a valid ID, please try again: ")
        if Choice2 == '1':
            Money1 = float(Money1) + float(DepositAmount)
            Money1 = round(Money1, 2)
            file = open('Accounts1/Money1.txt', 'w')
            file.write(str(Money1))
            file.close()
        elif Choice2 == '2':
            Money2 = float(Money2) + float(DepositAmount)
            Money2 = round(Money2, 2)
            file = open('Accounts1/Money2.txt', 'w')
            file.write(str(Money2))
            file.close()
        elif Choice2 == '3':
            Money3 = float(Money3) + float(DepositAmount)
            Money3 = round(Money3, 2)
            file = open('Accounts1/Money3.txt', 'w')
            file.write(str(Money3))
            file.close()
        elif Choice2 == '4':
            Money4 = float(Money4) + float(DepositAmount)
            Money4 = round(Money4, 2)
            file = open('Accounts1/Money4.txt', 'w')
            file.write(str(Money4))
            file.close()
        elif Choice2 == '5':
            Money5 = float(Money5) + float(DepositAmount)
            Money5 = round(Money5, 2)
            file = open('Accounts1/Money5.txt', 'w')
            file.write(str(Money5))
            file.close()
        elif Choice2 == '6':
            Money6 = float(Money6) + float(DepositAmount)
            Money6 = round(Money6, 2)
            file = open('Accounts1/Money6.txt', 'w')
            file.write(str(Money6))
            file.close()
        elif Choice2 == '7':
            Money7 = float(Money7) + float(DepositAmount)
            Money7 = round(Money7, 2)
            file = open('Accounts1/Money7.txt', 'w')
            file.write(str(Money7))
            file.close()
        elif Choice2 == '8':
            Money8 = float(Money8) + float(DepositAmount)
            Money8 = round(Money8, 2)
            file = open('Accounts1/Money8.txt', 'w')
            file.write(str(Money8))
            file.close()
        elif Choice2 == '9':
            Money9 = float(Money9) + float(DepositAmount)
            Money9 = round(Money9, 2)
            file = open('Accounts1/Money9.txt', 'w')
            file.write(str(Money9))
            file.close()
        elif Choice2 == '10':
            Money10 = float(Money10) + float(DepositAmount)
            Money10 = round(Money10, 2)
            file = open('Accounts1/Money10.txt', 'w')
            file.write(str(Money10))
            file.close()
        elif Choice2 == '11':
            Money11 = float(Money11) + float(DepositAmount)
            Money11 = round(Money11, 2)
            file = open('Accounts1/Money11.txt', 'w')
            file.write(str(Money11))
            file.close()
        elif Choice2 == '12':
           Money12 = float(Money12) + float(DepositAmount)
           Money12 = round(Money12, 2)
           file = open('Accounts1/Money12.txt', 'w')
           file.write(str(Money12))
           file.close()
        elif Choice2 == '13':
            Money13 = float(Money13) + float(DepositAmount)
            Money13 = round(Money13, 2)
            file = open('Accounts1/Money13.txt', 'w')
            file.write(str(Money13))
            file.close()
        elif Choice2 == '14':
            Money14 = float(Money14) + float(DepositAmount)
            Money14 = round(Money14, 2)
            file = open('Accounts1/Money14.txt', 'w')
            file.write(str(Money14))
            file.close()
        elif Choice2 == '15':
            Money15 = float(Money15) + float(DepositAmount)
            Money15 = round(Money15, 2)
            file = open('Accounts1/Money15.txt', 'w')
            file.write(str(Money15))
            file.close()
        elif Choice2 == '16':
            Money16 = float(Money16) + float(DepositAmount)
            Money16 = round(Money16, 2)
            file = open('Accounts1/Money16.txt', 'w')
            file.write(str(Money16))
            file.close()
        elif Choice2 == '17':
            Money17 = float(Money17) + float(DepositAmount)
            Money17 = round(Money17, 2)
            file = open('Accounts1/Money17.txt', 'w')
            file.write(str(Money17))
            file.close()
        elif Choice2 == '18':
            Money18 = float(Money18) + float(DepositAmount)
            Money18 = round(Money18, 2)
            file = open('Accounts1/Money18.txt', 'w')
            file.write(str(Money18))
            file.close()
        elif Choice2 == '19':
            Money19 = float(Money19) + float(DepositAmount)
            Money19 = round(Money19, 2)
            file = open('Accounts1/Money19.txt', 'w')
            file.write(str(Money19))
            file.close()
        elif Choice2 == '20':
            Money20 = float(Money20) + float(DepositAmount)
            Money20 = round(Money20, 2)
            file = open('Accounts1/Money20.txt', 'w')
            file.write(str(Money20))
            file.close()
        elif Choice2 == '21':
            Money21 = float(Money21) + float(DepositAmount)
            Money21 = round(Money21, 2)
            file = open('Accounts1/Money21.txt', 'w')
            file.write(str(Money21))
            file.close()
        elif Choice2 == '22':
            Money22 = float(Money22) + float(DepositAmount)
            Money22 = round(Money22, 2)
            file = open('Accounts1/Money22.txt', 'w')
            file.write(str(Money22))
            file.close()
        elif Choice2 == '23':
            Money23 = float(Money23) + float(DepositAmount)
            Money23 = round(Money23, 2)
            file = open('Accounts1/Money23.txt', 'w')
            file.write(str(Money23))
            file.close()
        elif Choice2 == '24':
            Money24 = float(Money24) + float(DepositAmount)
            Money24 = round(Money24, 2)
            file = open('Accounts1/Money24.txt', 'w')
            file.write(str(Money24))
            file.close()
        elif Choice2 == '25':
            Money25 = float(Money25) + float(DepositAmount)
            Money25 = round(Money25, 2)
            file = open('Accounts1/Money25.txt', 'w')
            file.write(str(Money25))
            file.close()
        elif Choice2 == '26':
            Money26 = float(Money26) + float(DepositAmount)
            Money26 = round(Money26, 2)
            file = open('Accounts1/Money26.txt', 'w')
            file.write(str(Money26))
            file.close()
        elif Choice2 == '27':
            Money27 = float(Money27) + float(DepositAmount)
            Money27 = round(Money27, 2)
            file = open('Accounts1/Money27.txt', 'w')
            file.write(str(Money27))
            file.close()
        elif Choice2 == '28':
            Money28 = float(Money28) + float(DepositAmount)
            Money28 = round(Money28, 2)
            file = open('Accounts1/Money28.txt', 'w')
            file.write(str(Money28))
            file.close()
        elif Choice2 == '29':
            Money29 = float(Money29) + float(DepositAmount)
            Money29 = round(Money29, 2)
            file = open('Accounts1/Money29.txt', 'w')
            file.write(str(Money29))
            file.close()
        elif Choice2 == '30':
            Money30 = float(Money30) + float(DepositAmount)
            Money30 = round(Money30, 2)
            file = open('Accounts1/Money30.txt', 'w')
            file.write(str(Money30))
            file.close()
    elif Choice1 == 'w':
        WithdrawAmount = input('How much do you want to withdraw? $')
        Choice2 = input("Type the Student ID number here: ")
        while Choice2 != '1' and Choice2 != '2' and Choice2 != '3' and Choice2 != '4' and Choice2 != '5' and Choice2 != '6' and Choice2 != '7' and\
        Choice2 != '8' and Choice2 != '9' and Choice2 != '10' and Choice2 != '11' and Choice2 != '12' and Choice2 != '13' and Choice2 != '14' and\
        Choice2 != '15' and Choice2 != '16' and Choice2 != '17' and Choice2 != '18' and Choice2 != '19' and Choice2 != '20' and Choice2 != '21' and\
        Choice2 != '22' and Choice2 != '23' and Choice2 != '24' and Choice2 != '25' and Choice2 != '26' and Choice2 != '27' and\
        Choice2 != '28' and Choice2 != '29' and Choice2 != '30':
            Choice2 = input("Not a valid ID, please try again: ")
        if Choice2 == '1':
            Money1 = float(Money1) - float(WithdrawAmount)
            Money1 = round(Money1, 2)
            file = open('Accounts1/Money1.txt', 'w')
            file.write(str(Money1))
            file.close()
        elif Choice2 == '2':
            Money2 = float(Money2) - float(WithdrawAmount)
            Money2 = round(Money2, 2)
            file = open('Accounts1/Money2.txt', 'w')
            file.write(str(Money2))
            file.close()
        elif Choice2 == '3':
            Money3 = float(Money3) - float(WithdrawAmount)
            Money3 = round(Money3, 2)
            file = open('Accounts1/Money3.txt', 'w')
            file.write(str(Money3))
            file.close()
        elif Choice2 == '4':
            Money4 = float(Money4) - float(WithdrawAmount)
            Money4 = round(Money4, 2)
            file = open('Accounts1/Money4.txt', 'w')
            file.write(str(Money4))
            file.close()
        elif Choice2 == '5':
            Money5 = float(Money5) - float(WithdrawAmount)
            Money5 = round(Money5, 2)
            file = open('Accounts1/Money5.txt', 'w')
            file.write(str(Money5))
            file.close()
        elif Choice2 == '6':
            Money6 = float(Money6) - float(WithdrawAmount)
            Money6 = round(Money6, 2)
            file = open('Accounts1/Money6.txt', 'w')
            file.write(str(Money6))
            file.close()
        elif Choice2 == '7':
            Money7 = float(Money7) - float(WithdrawAmount)
            Money7 = round(Money7, 2)
            file = open('Accounts1/Money7.txt', 'w')
            file.write(str(Money7))
            file.close()
        elif Choice2 == '8':
            Money8 = float(Money8) - float(WithdrawAmount)
            Money8 = round(Money8, 2)
            file = open('Accounts1/Money8.txt', 'w')
            file.write(str(Money8))
            file.close()
        elif Choice2 == '9':
            Money9 = float(Money9) - float(WithdrawAmount)
            Money9 = round(Money9, 2)
            file = open('Accounts1/Money9.txt', 'w')
            file.write(str(Money9))
            file.close()
        elif Choice2 == '10':
            Money10 = float(Money10) - float(WithdrawAmount)
            Money10 = round(Money10, 2)
            file = open('Accounts1/Money10.txt', 'w')
            file.write(str(Money10))
            file.close()
        elif Choice2 == '11':
            Money11 = float(Money11) - float(WithdrawAmount)
            Money11 = round(Money11, 2)
            file = open('Accounts1/Money11.txt', 'w')
            file.write(str(Money11))
            file.close()
        elif Choice2 == '12':
            Money12 = float(Money12) - float(WithdrawAmount)
            Money12 = round(Money12, 2)
            file = open('Accounts1/Money12.txt', 'w')
            file.write(str(Money12))
            file.close()
        elif Choice2 == '13':
            Money13 = float(Money13) - float(WithdrawAmount)
            Money13 = round(Money13, 2)
            file = open('Accounts1/Money13.txt', 'w')
            file.write(str(Money13))
            file.close()
        elif Choice2 == '14':
            Money14 = float(Money14) - float(WithdrawAmount)
            Money14 = round(Money14, 2)
            file = open('Accounts1/Money14.txt', 'w')
            file.write(str(Money14))
            file.close()
        elif Choice2 == '15':
            Money15 = float(Money15) - float(WithdrawAmount)
            Money15 = round(Money15, 2)
            file = open('Accounts1/Money15.txt', 'w')
            file.write(str(Money15))
            file.close()
        elif Choice2 == '16':
            Money16 = float(Money16) - float(WithdrawAmount)
            Money16 = round(Money16, 2)
            file = open('Accounts1/Money16.txt', 'w')
            file.write(str(Money16))
            file.close()
        elif Choice2 == '17':
            Money17 = float(Money17) - float(WithdrawAmount)
            Money17 = round(Money17, 2)
            file = open('Accounts1/Money17.txt', 'w')
            file.write(str(Money17))
            file.close()
        elif Choice2 == '18':
            Money18 = float(Money18) - float(WithdrawAmount)
            Money18 = round(Money18, 2)
            file = open('Accounts1/Money18.txt', 'w')
            file.write(str(Money18))
            file.close()
        elif Choice2 == '19':
            Money19 = float(Money19) - float(WithdrawAmount)
            Money19 = round(Money19, 2)
            file = open('Accounts1/Money19.txt', 'w')
            file.write(str(Money19))
            file.close()
        elif Choice2 == '20':
            Money20 = float(Money20) - float(WithdrawAmount)
            Money20 = round(Money20, 2)
            file = open('Accounts1/Money20.txt', 'w')
            file.write(str(Money20))
            file.close()
        elif Choice2 == '21':
            Money21 = float(Money21) - float(WithdrawAmount)
            Money21 = round(Money21, 2)
            file = open('Accounts1/Money21.txt', 'w')
            file.write(str(Money21))
            file.close()
        elif Choice2 == '22':
            Money22 = float(Money22) - float(WithdrawAmount)
            Money22 = round(Money22, 2)
            file = open('Accounts1/Money22.txt', 'w')
            file.write(str(Money22))
            file.close()
        elif Choice2 == '23':
            Money23 = float(Money23) - float(WithdrawAmount)
            Money23 = round(Money23, 2)
            file = open('Accounts1/Money23.txt', 'w')
            file.write(str(Money23))
            file.close()
        elif Choice2 == '24':
            Money24 = float(Money24) - float(WithdrawAmount)
            Money24 = round(Money24, 2)
            file = open('Accounts1/Money24.txt', 'w')
            file.write(str(Money24))
            file.close()
        elif Choice2 == '25':
            Money25 = float(Money25) - float(WithdrawAmount)
            Money25 = round(Money25, 2)
            file = open('Accounts1/Money25.txt', 'w')
            file.write(str(Money25))
            file.close()
        elif Choice2 == '26':
            Money26 = float(Money26) - float(WithdrawAmount)
            Money26 = round(Money26, 2)
            file = open('Accounts1/Money26.txt', 'w')
            file.write(str(Money26))
            file.close()
        elif Choice2 == '27':
            Money27 = float(Money27) - float(WithdrawAmount)
            Money27 = round(Money27, 2)
            file = open('Accounts1/Money27.txt', 'w')
            file.write(str(Money27))
            file.close()
        elif Choice2 == '28':
            Money28 = float(Money28) - float(WithdrawAmount)
            Money28 = round(Money28, 2)
            file = open('Accounts1/Money28.txt', 'w')
            file.write(str(Money28))
            file.close()
        elif Choice2 == '29':
            Money29 = float(Money29) - float(WithdrawAmount)
            Money29 = round(Money29, 2)
            file = open('Accounts1/Money29.txt', 'w')
            file.write(str(Money29))
            file.close()
        elif Choice2 == '30':
            Money30 = float(Money30) - float(WithdrawAmount)
            Money30 = round(Money30, 2)
            file = open('Accounts1/Money30.txt', 'w')
            file.write(str(Money30))
            file.close()